config/routes.rb
Highlights3::Application.routes.draw do
  get 'home/index'

  devise_for :users

  resources :users, only: :show

  resources :highlights

  resources :charges

  namespace :admin do
    resources :users
    resources :highlight_types
    resources :highlights
    resources :admin, only: :index
  end

  root 'home#index'

  

end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

	mount_uploader :highlight_file, HighlightFileUploader

	state_machine :initial => :pending do
		state :pending
		state :processing
		state :accepted
		state :in_production
		state :complete

		event :paid do
			transition :pending => :processing
		end

		event :accept do
			transition :processing => :accepted
		end

		event :start_production do
			transition :accepted => :in_production
		end

		event :complete do
			transition :in_production => :complete
		end

		event :reset do
			transition [:complete, :in_production, :accepted, :pending] => :processing
		end

		after_transition :to => :paid, :do => :paid
		after_transition :to => :accepted,  :do => :accepted
		after_transition :to => :in_production,  :do => :in_production
		after_transition :to => :complete, :do => :complete
	end

	def paid
		AdminMailer.delay.new_order_email(self)
		UserMailer.delay.processing_email(self.user)
	end

	def accepted
		UserMailer.delay.accepted_email(self.user)
	end

	def in_production
		UserMailer.delay.production_email(self.user)
	end

	def complete
		UserMailer.delay.complete_email(self.user)
	end

	belongs_to :highlight_type,
		inverse_of: :highlights
	belongs_to :user,
		inverse_of: :highlights

	accepts_nested_attributes_for :user

	validates_presence_of :name

end

app/models/highlight_type.rb
class HighlightType < ActiveRecord::Base
	has_many :highlights,
		inverse_of: :highlight_type

	validates_presence_of :name
	validates_presence_of :description
	validates_presence_of :price
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :highlights,
  	inverse_of: :user

  accepts_nested_attributes_for :highlights 

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	before_action :authenticate_user!
	before_action :is_admin?

	def index
	end

end

app/controllers/admin/highlight_types_controller.rb
class Admin::HighlightTypesController < ApplicationController
	before_action :authenticate_user!
	before_action :is_admin?

	def index
		@highlight_types = HighlightType.all
	end

	def new
		@highlight_type = HighlightType.new
	end

	def create
		@highlight_type = HighlightType.create(highlight_type_params)
		if @highlight_type.save
			redirect_to admin_highlight_types_path, notice: 'Highlight Type Created.'
		else
			render 'new', notice: 'Highlight Type not created. Please try again.'
		end
	end

	def edit
		@highlight_type = HighlightType.find(params[:id])
	end

	def update
		@highlight_type = HighlightType.find(params[:id])
		if @highlight_type.update(highlight_type_params)
			redirect_to admin_highlight_types_path, notice: 'Highlight Type Updated'
		else
			render 'edit'
		end
	end

	def destroy
		@highlight_type = HighlightType.find(params[:id])
		@highlight_type.destroy
		redirect_to admin_highlight_types_path, notice: 'Highlight Type Deleted'
	end

	private
		def highlight_type_params
			params.require(:highlight_type).permit(:name, :description, :price, :active)
		end

end

app/controllers/admin/highlights_controller.rb
class Admin::HighlightsController < ApplicationController
	before_action :authenticate_user!
	before_action :is_admin?

	def index
		@highlights = Highlight.all.order("created_at DESC")
	end

	def show
		@highlight = Highlight.find(params[:id])
	end

	def edit
		@highlight = Highlight.find(params[:id])
	end

	def update
		@highlight = Highlight.find(params[:id])

		if @highlight.update(highlight_params)
			redirect_to admin_highlight_path(@highlight), notice: 'State Changed'	
		end
	end

	def destroy
		@highlight = Highlight.find(params[:id])
		@highlight.destroy

		redirect_to admin_highlights_path, notice: 'Highlight Deleted'
	end

	private

		def highlight_params
			params.require(:highlight).permit(:state_event, :highlight_file)
		end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :is_admin?

	def index
		@users = User.all.order("created_at DESC")
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to admin_user_path(@user), notice: 'User Updated'
		else
			redirect_to edit_admin_user_path(@user), notice: 'User Not Updated'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to admin_users_path, notice: 'User Deleted'
	end

	private

		def user_params
			params.require(:user).permit(:admin)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def after_sign_in_path_for(resource)
  	user_path(current_user)
	end

  private

    def is_admin?
      redirect_to root_path, notice: 'You are not authorized to view that page.' unless current_user.admin
    end


  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_path, :alert => exception.message
  # end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	before_action :authenticate_user!

	def new
		@highlight = current_user.highlights.last
		@highlight_type = @highlight.highlight_type
	end

	def create
	  @highlight = current_user.highlights.last
	  @highlight_type = @highlight.highlight_type
	  @amount = @highlight.highlight_type.price


	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	  @highlight.paid

			rescue Stripe::CardError => e
		  	redirect_to new_charge_path, notice: e.message

	end

end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
	before_action :authenticate_user!, except: [:new, :create]
	before_action :edit_highlight?, only: [:edit, :update, :destroy]

	def show
		@highlight = current_user.highlights.find(params[:id])
		@highlight_type = @highlight.highlight_type
	end

	def new
		@highlight = Highlight.new
		@highlight.build_user unless current_user
		@highlight_type = HighlightType.find(params[:highlight_type_id])
	end

	def create
		@highlight = Highlight.new(highlight_params)
		@highlight.user_id = current_user.id if current_user

		if @highlight.save
			sign_in @highlight.user
			redirect_to new_charge_path, notice: 'Highlight Created'
		else
			redirect_to new_highlight_path
		end
	end

	def edit
		@highlight = current_user.highlights.find(params[:id])
		@highlight_type = @highlight.highlight_type
	end

	def update
		@highlight = current_user.highlights.where(id: params[:id]).first

		if @highlight.update(highlight_params)
			redirect_to new_charge_path, notice: 'Highlight Updated'
		else
			render 'edit'
		end
	end

	def destroy
		@highlight = current_user.highlights.find(params[:id])
		@highlight.destroy
		redirect_to root_path, notice: 'Highlight Deleted / Order Cancelled'
	end
	
	private

		def highlight_params
			params.require(:highlight).permit(:name, :highlight_type_id, :nickname, :hometown, :school, :previous_teams, :bats, :throwing_hand, :position, :age, :family_friends, :opponent, :scenario, :notes, user_attributes: [:email, :password, :password_confirmation])
		end

		def edit_highlight?
			@highlight = Highlight.find(params[:id])
			redirect_to user_path(current_user), notice: 'You are not authorized to perform that action' unless @highlight.state == 'pending'
		end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@highlight_types = HighlightType.all
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = current_user
		@highlights = current_user.highlights.order("created_at DESC")
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admin/index.html.erb
<h1>admin index</h1>

app/views/admin/highlight_types/_highlight_type_form.html.erb
<%= simple_form_for [:admin, @highlight_type] do |f| %>
	<%= f.input :name, label: 'Highlight Type Name' %>
	<%= f.input :description, label: 'Highlight Type Description' %>
	<%= f.input :price, label: 'Highlight Type Price' %>
	<%= f.input :active, label: 'Highlight Type Status' %>
	<%= f.submit 'Submit' %>
<%- end %>

app/views/admin/highlight_types/edit.html.erb
<%= render 'highlight_type_form' %>

<%= link_to 'Delete This Highlight Type', [:admin, @highlight_type], method: :delete, data: { confirm: "Are you sure?" } %>

app/views/admin/highlight_types/index.html.erb
<%= link_to 'Create A New Highlight Type', new_admin_highlight_type_path %>

<%- @highlight_types.each do |type| %>
	<ul>
		<li><%= type.name %></li>
		<li><%= type.description %></li>
		<li><%= type.price %></li>
		<li>Active: <%= type.active%></li>
		<li><%= link_to 'Edit This Highlight Type', edit_admin_highlight_type_path(type) %></li>
		<li><%= link_to 'Delete This Highlight Type', [:admin, type], method: :delete, data: { confirm: "Are you sure?" } %></li>
	</ul>
<%- end %>

app/views/admin/highlight_types/new.html.erb
<%= render 'highlight_type_form' %>

app/views/admin/highlights/index.html.erb
<div class="admin-highlights-index">
	<%- @highlights.each do |highlight| %>
		<p>
			<%= highlight.user.email %>
			<%= highlight.created_at.strftime("%Y-%m-%d") %>
			<%= highlight.highlight_type.name %>
			<%= highlight.state %>
			<%= link_to 'Manage Highlight', admin_highlight_path(highlight) %>
		</p>
<%- end %>
</div>

app/views/admin/highlights/show.html.erb
<div class="admin-highlights-show">
	<ul>
		<li><%= @highlight.user.email %></li>
		<li><%= @highlight.highlight_type.name %></li>
		<li><%= @highlight.id %></li>
		<li><%= @highlight.name %></li>
		<li><%= @highlight.nickname %></li>
		<li><%= @highlight.hometown %></li>
		<li><%= @highlight.school %></li>
		<li><%= @highlight.previous_teams %></li>
		<li><%= @highlight.bats %></li>
		<li><%= @highlight.throwing_hand %></li>
		<li><%= @highlight.position %></li>
		<li><%= @highlight.age %></li>
		<li><%= @highlight.family_friends %></li>
		<li><%= @highlight.opponent %></li>
		<li><%= @highlight.scenario %></li>
		<li><%= @highlight.notes %></li>
		<li><%= @highlight.created_at.strftime("%Y-%m-%d") %></li>
		<li><%= @highlight.state %></li>
		<%- unless @highlight.highlight_file.blank? %>
			<li><%= link_to 'Highlight', @highlight.highlight_file.url %></li>
		<%- end %>
	</ul>

	<%= simple_form_for [:admin, @highlight] do |f| %>
		<%- if @highlight.state == 'processing' %>
			<%= f.input :state_event, as: :hidden, input_html: { value: 'accept' } %>
			<%= f.submit 'Accept Highlight' %>
		<%- elsif @highlight.state == 'accepted' %>
			<%= f.input :state_event, as: :hidden, input_html: { value: 'start_production' } %>
			<%= f.submit 'Start Production' %>
		<%- elsif @highlight.state == 'in_production' %>
			<%= f.input :state_event, as: :hidden, input_html: { value: 'complete' } %>
			<%= f.input :highlight_file, as: :file %>
			<%= f.submit 'Complete Highlight' %>
		<%- elsif @highlight.state == 'complete' %>
			<%= f.input :state_event, as: :hidden, input_html: { value: 'reset' } %>
			<%= f.input :highlight_file, as: :file %>
			<%= f.submit 'Reset to Processing' %>
		<%- end %>
	<%- end %>

	<%= button_to 'Delete Highlight', [:admin, @highlight], method: :delete, data: { confirm: "Are you sure?" }%>

</div>

app/views/admin/users/edit.html.erb
<h3>User Id: <%= @user.id %></h3>
<h3>User Email: <%= @user.email %></h3>

<%= simple_form_for [:admin, @user] do |f| %>
	<%= f.input :admin, as: :select, label: 'User Admin?' %>
	<%= f.submit 'Update User' %>
<%- end %>

<%= link_to 'Delete This User', [:admin, @user], method: :delete, data: { confirm: "Are you sure?" } %>

app/views/admin/users/index.html.erb
<div class="admin-users-index">
	<%- @users.each do |user| %>
		<p>
			<%= user.id %>
			<%= user.email %>
			<%= user.admin %>
			<%= user.highlights.count %>
			<%= user.created_at.strftime("%Y-%m-%d") %>
			<%= link_to "View User #{user.id}'s Details", admin_user_path(user) %>
		</p>
	<%- end %>
</div>

app/views/admin/users/show.html.erb
<div class="admin-users-show">
	<ul>
		<li>User's ID Number: <%= @user.id%></li>
		<li>User's Email: <%= @user.email %></li>
		<li>Is User an Admin: <%= @user.admin %></li>
		<li>User Signed up on: <%= @user.created_at.strftime("%Y-%m-%d") %></li>
		<h3>User's Highlights: </h3>
			<ol>
				<%- @user.highlights.each do |highlight| %>
					<li>
						<ul>
							<li><%= highlight.name %></li>
							<li><%= highlight.highlight_type.name %></li>
							<li><%= highlight.created_at.strftime("%Y-%m-%d") %></li>
							<li><%= highlight.state %></li>
							<li><%= link_to 'Highlight Details', admin_highlight_path(highlight) %></li>
							<%- unless highlight.highlight_file.blank? %>
								<li><%= link_to 'Highlight', highlight.highlight_file.url %></li>
							<%- end %>
						</ul>
					</li>
				<%- end %>
			</ol>
		<li><%= link_to 'Edit User', edit_admin_user_path(@user) %></li>
	</ul>
</div>

app/views/charges/create.html.erb
<div class="charges-create">
	<h2>Thanks, you paid <strong><%= number_to_currency(@amount * 0.01) %></strong>!</h2>

	<h3>Expect an email confirming your order shortly. If you don't receive an email please <%= mail_to 'postmaster@app18042297.mailgun.org', 'let us know.' %></h3>
	<h3>Of course you can always log into <%= link_to 'your account', user_path(current_user) %> to check on your order</h3>
	<h3>Otherwise sit back and relax. We'll email you when your highlight is accepted, when it goes into production and finally when it's complete and ready for download.</h3>
</div>

app/views/charges/new.html.erb
<%= render 'highlights/details' %>

app/views/highlights/_details.html.erb
<div class="highlight-details">
	<h2>Here are all of your highlight details.</h2>

	<table>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Name:</td>
			<td><%= @highlight.name %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Nickname:</td>
			<td><%= @highlight.nickname %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Hometown:</td>
			<td><%= @highlight.hometown %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Bats:</td>
			<td><%= @highlight.bats %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Throwing Hand:</td>
			<td><%= @highlight.throwing_hand %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Scenario:</td>
			<td><%= @highlight.scenario %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Position:</td>
			<td><%= @highlight.position %></td>
		</tr>
		<%- if @highlight.highlight_type_id > 1 %>
			<tr>
				<td class="old_baseball_list"></td>
				<td>School:</td>
				<td><%= @highlight.school %></td>
			</tr>
			<tr>
				<td class="old_baseball_list"></td>
				<td>Age:</td>
				<td><%= @highlight.age %></td>
			</tr>
		<%- end %>
		<%- if @highlight.highlight_type_id > 2 %>
			<tr>
				<td class="old_baseball_list"></td>
				<td>Others to reference:</td>
				<td><%= @highlight.family_friends %></td>
			</tr>
			<tr>
				<td class="old_baseball_list"></td>
				<td>Opponent:</td>
				<td><%= @highlight.opponent %></td>
			</tr>
		<%- end %>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Additional Info:</td>
			<td><%= @highlight.notes %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Type of Highlight:</td>
			<td><%= @highlight_type.name %></td>
		</tr>
		<tr>
			<td class="old_baseball_list"></td>
			<td>Order Status:</td>
			<td><%= @highlight.state %></td>
		</tr>
		<%- unless @highlight.highlight_file.blank? %>
			<tr>
				<td class="old_baseball_list"></td>
				<td>Your Highlight:</td>
				<td><%= link_to 'Download', @highlight.highlight_file.url %></td>
			</tr>
		<%- end %>
	</table>

	<%- if @highlight.state == 'pending' %>
		<button><%= link_to 'Click to make changes', edit_highlight_path(@highlight) %></button>
		<button><%= link_to 'Cancel / Delete This Highlight', @highlight, method: :delete, data: { confirm: "Are you sure?" } %></button>
		<h3>Your Custom Highlight Costs: <%= number_to_currency(@highlight_type.price * 0.01) %></h3>
		<%= form_tag charges_path do %>

		  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="<%= @highlight_type.name %> Highlight"
		          data-amount="<%= @highlight_type.price %>"></script>

		<% end %>
	<%- else %>
		<h3>You paid <%= number_to_currency(@highlight_type.price * 0.01)%> for your custom highlight.</h3>
	<%- end %>
</div>

app/views/shared/_details.erb
<div class="highlight-show">
	<h2>Here are all of your highlight details.</h2>

	<table>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Name:</td>
			<td><%= @highlight.name %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Nickname:</td>
			<td><%= @highlight.nickname %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Hometown:</td>
			<td><%= @highlight.hometown %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Bats:</td>
			<td><%= @highlight.bats %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Throwing Hand:</td>
			<td><%= @highlight.throwing_hand %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Scenario:</td>
			<td><%= @highlight.scenario %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Position:</td>
			<td><%= @highlight.position %></td>
		</tr>
		<%- if @highlight.highlight_type_id > 1 %>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>School:</td>
				<td><%= @highlight.school %></td>
			</tr>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Age:</td>
				<td><%= @highlight.age %></td>
			</tr>
		<%- end %>
		<%- if @highlight.highlight_type_id > 2 %>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Others to reference:</td>
				<td><%= @highlight.family_friends %></td>
			</tr>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Opponent:</td>
				<td><%= @highlight.opponent %></td>
			</tr>
		<%- end %>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Additional Info:</td>
			<td><%= @highlight.notes %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Type of Highlight:</td>
			<td><%= @highlight_type.name %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Order Status:</td>
			<td><%= @highlight.state %></td>
		</tr>
		<%- unless @highlight.highlight_file.blank? %>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Your Highlight:</td>
				<td><%= link_to 'Download', @highlight.highlight_file.url %></td>
			</tr>
		<%- end %>
	</table>

	<%- if @highlight.state == 'pending' %>
		<button><%= link_to 'Click to make changes', edit_highlight_path(@highlight) %></button>
		<button><%= link_to 'Cancel / Delete This Highlight', @highlight, method: :delete, data: { confirm: "Are you sure?" } %></button>
		<h3>Your Custom Highlight Costs: <%= number_to_currency(@highlight_type.price * 0.01) %></h3>
		<%= form_tag charges_path do %>

		  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="<%= @highlight_type.name %> Highlight"
		          data-amount="<%= @highlight_type.price %>"></script>

		<% end %>
	<%- else %>
		<h3>You paid <%= number_to_currency(@highlight_type.price * 0.01)%> for your custom highlight.</h3>
	<%- end %>
</div>

app/views/shared/_header.html.erb
<header>
	<div class="header-content btcf">
		<div id="header-baseball">
			<%= image_tag 'old_baseball_small.png' %>
		</div>
		<div id="header-links">
			<%- if user_signed_in? %>
				<ul>
					<li><button><%= link_to 'My Account', user_path(current_user) %></button></li>
					<li><button><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></button></li>
					<%- if current_user.admin %>
						<li><button><%= link_to "Admin", admin_admin_index_path %></button></li>
					<%- end %>
				</ul>
			<%- else %>
				<ul>
					<li><button><%= link_to 'Sign In', new_user_session_path %></button></li>
				</ul>
			<%- end %>
		</div>
		<div id="logo">
			<h1><%= link_to 'You Make The Play!', root_path %></h1>
		</div>
	</div>
</header>

app/views/shared/_highlight_show.html.erb
<div class="highlight-show">
	<h2>Here are all of your highlight details.</h2>

	<table>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Name:</td>
			<td><%= @highlight.name %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Nickname:</td>
			<td><%= @highlight.nickname %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Hometown:</td>
			<td><%= @highlight.hometown %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Bats:</td>
			<td><%= @highlight.bats %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Throwing Hand:</td>
			<td><%= @highlight.throwing_hand %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Scenario:</td>
			<td><%= @highlight.scenario %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Position:</td>
			<td><%= @highlight.position %></td>
		</tr>
		<%- if @highlight.highlight_type_id > 1 %>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>School:</td>
				<td><%= @highlight.school %></td>
			</tr>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Age:</td>
				<td><%= @highlight.age %></td>
			</tr>
		<%- end %>
		<%- if @highlight.highlight_type_id > 2 %>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Others to reference:</td>
				<td><%= @highlight.family_friends %></td>
			</tr>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Opponent:</td>
				<td><%= @highlight.opponent %></td>
			</tr>
		<%- end %>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Additional Info:</td>
			<td><%= @highlight.notes %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Type of Highlight:</td>
			<td><%= @highlight_type.name %></td>
		</tr>
		<tr>
			<td><%= image_tag 'old_baseball_list.png' %></td>
			<td>Order Status:</td>
			<td><%= @highlight.state %></td>
		</tr>
		<%- unless @highlight.highlight_file.blank? %>
			<tr>
				<td><%= image_tag 'old_baseball_list.png' %></td>
				<td>Your Highlight:</td>
				<td><%= link_to 'Download', @highlight.highlight_file.url %></td>
			</tr>
		<%- end %>
	</table>

	<%- if @highlight.state == 'pending' %>
		<button><%= link_to 'Click to make changes', edit_highlight_path(@highlight) %></button>
		<button><%= link_to 'Cancel / Delete This Highlight', @highlight, method: :delete, data: { confirm: "Are you sure?" } %></button>
		<h3>Your Custom Highlight Costs: <%= number_to_currency(@highlight_type.price * 0.01) %></h3>
		<%= form_tag charges_path do %>

		  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
		          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		          data-description="<%= @highlight_type.name %> Highlight"
		          data-amount="<%= @highlight_type.price %>"></script>

		<% end %>
	<%- else %>
		<h3>You paid <%= number_to_currency(@highlight_type.price * 0.01)%> for your custom highlight.</h3>
	<%- end %>
</div>

app/views/users/show.html.erb
<div class='user-show'>

	<h2><%= @user.email %></h2>

	<button><%= link_to 'Change Email or Password', edit_user_registration_path(@user) %></button>

	<h2>Your Personal Highlights</h2>

	<table>
		<th>Player's Name</th>
		<th>Highlight Type</th>
		<th>Date Created</th>
		<th>Order Status</th>
		<th>More</th>
		<th>Your Highlight</th>
		<%- @highlights.each do |highlight| %>
			<tr>
				<td><%= highlight.name %></td>
				<td><%= highlight.highlight_type.name %></td>
				<td><%= highlight.created_at.strftime("%Y-%m-%d") %></td>
				<td><%= highlight.state %></td>
				<td><%= link_to 'Details', highlight_path(highlight) %></td>
				<%- unless highlight.highlight_file.blank? %>
					<td><%= link_to 'Download', highlight.highlight_file.url %></td>
				<%- end %>
			</tr>
		<%- end %>		
	</table>

</div>